"""Static remediation language for guided review triage.

This module is deliberately data-only: guided wording must not be generated by
an agent or inferred from a finding message.
"""

from __future__ import annotations

REMEDIATION_CATALOG = (
    {
        "id": "hooks-absence",
        "members": ("journal_coverage", "protected_path_mutation:undeclared", "handoff:unconsumed"),
        "cause": "hooks 層未導入により journal 自動取得・intent 運用・handoff 消費が人力",
        "standard_fix": "hooks 復帰 WP の起票",
        "alt_fix": "AGENTS.md の Run discipline を再周知し手動運用を徹底",
        "question": "hooks 復帰 WP を次の作業として起票しますか?",
        "agent_executable": False,
    },
    {
        "id": "learning-backlog",
        "members": ("learning_backlog",),
        "cause": "未処理の learning backlog が残っている",
        "standard_fix": "loopeng learning promote --top 3 で起案し、draft を提示(適用はユーザー指示後)",
        "alt_fix": "backlog の確認を保留",
        "question": "backlog 上位の OKF report 起案を実行しますか?",
        "agent_executable": True,
    },
    {
        "id": "budget-recurrence",
        "members": ("budget_exceeded",),
        "cause": "同じ作業で予算超過が繰り返されている",
        "standard_fix": "しきい値見直し or 作業分割の提案",
        "alt_fix": "現行の予算設定を維持",
        "question": "しきい値見直しまたは作業分割を提案しますか?",
        "agent_executable": False,
    },
    {
        "id": "intent-overdeclaration",
        "members": ("intent_overdeclaration",),
        "cause": "intent の宣言粒度が変更範囲に対して過大",
        "standard_fix": "宣言粒度の見直し提案",
        "alt_fix": "現行の宣言粒度を維持",
        "question": "intent の宣言粒度を見直しますか?",
        "agent_executable": False,
    },
)

CATALOG_BY_ID = {entry["id"]: entry for entry in REMEDIATION_CATALOG}
