from __future__ import annotations

import hashlib
import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ._paths import agent_root
from .journal import sanitize_event


TRACE_EXCERPT_MAX = 2000
TRACE_DIR = agent_root("state", "trace")
TRACE_VIEW_DIR = agent_root("state", "reports", "trace")
_GENERATED = "<!-- GENERATED by loopeng trace render — DO NOT EDIT -->"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _trace_path(repo: Path, run_id: str) -> Path:
    return repo / TRACE_DIR / f"{run_id}.jsonl"


def _json_text(value: Any) -> str:
    if isinstance(value, str):
        return value
    return json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)


def _sanitized_text(value: Any) -> str:
    return _json_text(sanitize_event({"value": value})["value"])


def _excerpt(value: Any) -> tuple[str, str]:
    text = _sanitized_text(value)
    digest = "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()
    return text[:TRACE_EXCERPT_MAX], digest


def _read(repo: Path, run_id: str) -> list[dict[str, Any]]:
    try:
        return [json.loads(line) for line in _trace_path(repo, run_id).read_text(encoding="utf-8").splitlines() if line.strip()]
    except (FileNotFoundError, OSError, json.JSONDecodeError):
        return []


def _write(repo: Path, run_id: str, record: dict[str, Any]) -> None:
    path = _trace_path(repo, run_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(sanitize_event(record), ensure_ascii=False, sort_keys=True) + "\n")


def append_trace(repo: Path, run_id: str, record: dict[str, Any]) -> Path:
    """Append one sanitized trace record. Callers deliberately make this fail-open."""
    _write(repo, run_id, record)
    return _trace_path(repo, run_id)


def _next_call_ref(records: list[dict[str, Any]]) -> str:
    used = {str(item.get("call_ref")) for item in records if item.get("call_ref")}
    number = 1
    while f"t-{number:04d}" in used:
        number += 1
    return f"t-{number:04d}"


def record_pre(repo: Path, run_id: str, platform: str, payload: dict[str, Any]) -> Path:
    records = _read(repo, run_id)
    tool = str(payload.get("tool_name") or payload.get("tool") or "unknown")
    explicit = payload.get("tool_use_id") or payload.get("call_id")
    call_ref = str(explicit) if explicit else _next_call_ref(records)
    input_excerpt, input_digest = _excerpt(payload.get("tool_input"))
    record: dict[str, Any] = {
        "schema": 1, "ts": _now(), "phase": "pre", "run_id": run_id,
        "platform": platform, "tool_name": tool, "call_ref": call_ref,
        "pairing": "id" if explicit else "heuristic",
        "paths": list(payload.get("paths") or []), "input_excerpt": input_excerpt,
        "input_digest": input_digest, "tool_success": None,
    }
    return append_trace(repo, run_id, record)


def _pairing(records: list[dict[str, Any]], tool: str, explicit: Any) -> tuple[str, str | None, float | None]:
    pre = [item for item in records if item.get("phase") == "pre" and item.get("tool_name") == tool]
    if explicit:
        matches = [item for item in pre if item.get("call_ref") == str(explicit)]
        if matches:
            item = matches[-1]
            if any(record.get("phase") == "post" and record.get("call_ref") == item.get("call_ref") for record in records):
                return "unmatched", None, None
            return "id", str(item.get("call_ref")), _elapsed(item.get("ts"))
        return "unmatched", None, None
    pending = [item for item in pre if not any(record.get("phase") == "post" and record.get("call_ref") == item.get("call_ref") for record in records)]
    if len(pending) > 1:
        return "ambiguous", None, None
    if pending:
        item = pending[-1]
        return "heuristic", str(item.get("call_ref")), _elapsed(item.get("ts"))
    return "unmatched", None, None


def _elapsed(ts: Any) -> float | None:
    try:
        started = datetime.fromisoformat(str(ts))
        return max(0.0, (datetime.now(timezone.utc) - started).total_seconds() * 1000)
    except (TypeError, ValueError):
        return None


def record_post(repo: Path, run_id: str, platform: str, payload: dict[str, Any]) -> Path:
    records = _read(repo, run_id)
    tool = str(payload.get("tool_name") or payload.get("tool") or "unknown")
    explicit = payload.get("tool_use_id") or payload.get("call_id")
    pairing, call_ref, duration = _pairing(records, tool, explicit)
    response_excerpt, response_digest = _excerpt(payload.get("tool_response"))
    success = payload.get("tool_success", payload.get("success", True))
    if "exit_code" in payload:
        success = payload.get("exit_code") == 0
    record: dict[str, Any] = {
        "schema": 1, "ts": _now(), "phase": "post", "run_id": run_id,
        "platform": platform, "tool_name": tool, "call_ref": call_ref or _next_call_ref(records),
        "pairing": pairing, "paths": list(payload.get("paths") or []),
        "response_excerpt": response_excerpt, "response_digest": response_digest,
        "tool_success": bool(success), "duration_ms": max(1, round(duration)) if duration is not None and pairing != "ambiguous" else None,
    }
    return append_trace(repo, run_id, record)


def record_deny(repo: Path, run_id: str, platform: str, payload: dict[str, Any], reason: str) -> Path:
    records = _read(repo, run_id)
    tool = str(payload.get("tool_name") or payload.get("tool") or "unknown")
    pre = [item for item in reversed(records) if item.get("phase") == "pre" and item.get("tool_name") == tool]
    call_ref = str(pre[0].get("call_ref")) if pre else _next_call_ref(records)
    return append_trace(repo, run_id, {
        "schema": 1, "ts": _now(), "phase": "deny", "run_id": run_id,
        "platform": platform, "tool_name": tool, "call_ref": call_ref,
        "pairing": "id" if payload.get("tool_use_id") or payload.get("call_id") else "heuristic",
        "paths": list(payload.get("paths") or []), "tool_success": None,
        "deny_reason": reason,
    })


def _journal(repo: Path, run_id: str) -> list[dict[str, Any]]:
    path = repo / agent_root("state", "journal") / f"{run_id}.jsonl"
    try:
        return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    except (FileNotFoundError, OSError, json.JSONDecodeError):
        return []


def _fence(text: str) -> str:
    longest = max((len(part) for part in text.split("\n") if part.strip()), default=0)
    ticks = max(3, longest + 1 if "`" in text else 3)
    return "`" * ticks


def _target(record: dict[str, Any]) -> str:
    paths = record.get("paths") or []
    if paths:
        return str(paths[0])
    text = record.get("input_excerpt") or record.get("response_excerpt") or ""
    return str(text).replace("\n", " ")[:60]


def render_run(repo: Path, run_id: str) -> Path:
    records = _read(repo, run_id)
    journals = _journal(repo, run_id)
    posts = [item for item in records if item.get("phase") == "post"]
    denies = [item for item in records if item.get("phase") == "deny"]
    tools = Counter(str(item.get("tool_name") or "unknown") for item in posts)
    durations = [item["duration_ms"] for item in posts if isinstance(item.get("duration_ms"), (int, float))]
    platforms = sorted({str(item.get("platform") or "unknown") for item in records})
    platform = platforms[0] if len(platforms) == 1 else ", ".join(platforms) or "unknown"
    lines = [_GENERATED, "", "# Tool trace", "", "## Summary", "", f"- run_id: {run_id}", f"- platform: {platform}", f"- calls: {len(posts)}", f"- total duration_ms: {round(sum(durations))}", f"- unmatched/ambiguous: {sum(item.get('pairing') in {'unmatched', 'ambiguous'} for item in posts)}", "", "| tool | count |", "| --- | ---: |"]
    lines.extend(f"| {tool} | {count} |" for tool, count in sorted(tools.items()))
    lines += ["", "## Timeline", "", "| # | ts | tool | target | success | duration_ms | pairing |", "| ---: | --- | --- | --- | --- | ---: | --- |"]
    for number, item in enumerate(posts, 1):
        lines.append(f"| {number} | {item.get('ts', '')} | {item.get('tool_name', 'unknown')} | {_target(item)} | {item.get('tool_success')} | {item.get('duration_ms')} | {item.get('pairing', '')} |")
    lines += ["", "## Denied", ""]
    if denies:
        lines.extend(f"- `{item.get('call_ref', '')}` {item.get('tool_name', 'unknown')}: {item.get('deny_reason', '')}" for item in denies)
    else:
        lines.append("- none")
    lines += ["", "## Call details", ""]
    calls: dict[str, list[dict[str, Any]]] = {}
    order: list[str] = []
    for item in records:
        if item.get("phase") not in {"pre", "post"}:
            continue
        ref = str(item.get("call_ref") or _next_call_ref(records))
        if ref not in calls:
            calls[ref] = []
            order.append(ref)
        calls[ref].append(item)
    for ref in order:
        items = calls[ref]
        tool = next((str(item.get("tool_name") or "unknown") for item in items), "unknown")
        lines += [f"### {ref} {tool}", ""]
        for item in items:
            if item.get("input_excerpt") is not None:
                excerpt = str(item.get("input_excerpt", ""))
                lines += ["input_excerpt:", _fence(excerpt), excerpt, _fence(excerpt), ""]
            if item.get("response_excerpt") is not None:
                excerpt = str(item.get("response_excerpt", ""))
                lines += ["response_excerpt:", _fence(excerpt), excerpt, _fence(excerpt), ""]
    source = f"{TRACE_DIR.as_posix()}/{run_id}.jsonl"
    lines += ["## Provenance", "", "本ファイルは `loopeng trace render` による決定論的生成物であり、解釈・評価を含まない。", "", f"source: `{source}`", ""]
    output = repo / TRACE_VIEW_DIR / f"{run_id}.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    return output


def render_index(repo: Path) -> Path:
    trace_dir = repo / TRACE_DIR
    rows: list[tuple[str, str, str, str, int, int, int, int]] = []
    for path in sorted(trace_dir.glob("*.jsonl")) if trace_dir.is_dir() else []:
        run_id = path.stem
        records = _read(repo, run_id)
        journal = _journal(repo, run_id)
        posts = [item for item in records if item.get("phase") == "post"]
        start = next((item for item in journal if item.get("kind") == "run-start"), {})
        end = next((item for item in reversed(journal) if item.get("kind") == "run-end"), {})
        platform = str(start.get("agent") or next((item.get("platform") for item in records), "unknown"))
        rows.append((run_id, platform, str(start.get("timestamp") or ""), str(end.get("timestamp") or ""), len(posts), sum(item.get("tool_success") is False for item in posts), sum(item.get("phase") == "deny" for item in records), sum(item.get("pairing") in {"unmatched", "ambiguous"} for item in posts)))
    rows.sort(key=lambda row: (row[2], row[0]), reverse=True)
    lines = [_GENERATED, "", "# Tool trace index", "", "| run_id | platform | start | end | calls | failures | denied | unmatched | detail |", "| --- | --- | --- | --- | ---: | ---: | ---: | ---: | --- |"]
    for row in rows:
        lines.append(f"| {row[0]} | {row[1]} | {row[2]} | {row[3]} | {row[4]} | {row[5]} | {row[6]} | {row[7]} | [{row[0]}]({row[0]}.md) |")
    output = repo / TRACE_VIEW_DIR / "index.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output


def render(repo: Path, run_id: str | None = None, all_runs: bool = False) -> list[Path]:
    if all_runs:
        paths = [render_run(repo, path.stem) for path in sorted((repo / TRACE_DIR).glob("*.jsonl"))]
        paths.append(render_index(repo))
        return paths
    if not run_id:
        raise ValueError("trace render requires --run or --all")
    return [render_run(repo, run_id), render_index(repo)]


def show(repo: Path, run_id: str) -> str:
    records = _read(repo, run_id)
    posts = [item for item in records if item.get("phase") == "post"]
    denied = [item for item in records if item.get("phase") == "deny"]
    return "\n".join([f"run {run_id}", f"calls={len(posts)} failures={sum(item.get('tool_success') is False for item in posts)} denied={len(denied)}", *[f"{item.get('ts')} {item.get('tool_name')} success={item.get('tool_success')} duration_ms={item.get('duration_ms')}" for item in posts]]) + "\n"
